name: 'Nightly Merge'
description: 'Automatically update the staging branch from the latest development one.'
author: 'Pablo Giraud-Carrier'
branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  staging_branch:
    description: 'Name of the staging branch'
    required: true
    default: 'staging'
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'Nightly Merge'
  user_email:
    description: 'User email for git commits'
    required: false
    default: 'pablo.giraud-carrier@rideyego.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
